server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://60.204.203.117:3306/blog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: blog
    password: BJ3AXbKcaScRZYcy
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379
#    password: 123

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath:mapper/**/*Mapper.xml

logging:
  level:
    fun.aprilsxz.blog.mapper: trace

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  openapi:
    title: blog接口文档
    description: "blog接口文档"
    email: xxxx@qq.com
    concat: yang
    url: https://aprilsxz.fun
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - fun.aprilsxz.blog.controller
huawei:
  obs:
    ak: XVMEKB4Q4OYRDZKLACAE
    sk: FaB0W6oLFcWbrKYg5kCoMV34Pjjq3bpB67gHK10I
    bucket-name: blog-aprilsxz
    end-point: https://obs.cn-east-3.myhuaweicloud.com

blog:
  jwt:
    location: classpath:blog.jks
    alias: blog
    password: yangyang
    tokenTTL: 30m
  auth:
    excludePaths:
      - /user/login
      - /user/register
      - /article/**
      - /dynamic/**
      - /**
